apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5433

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector :
    app.kubernetes.io/name: postgres
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5433
  